app/routes.py
import json
import logging
import boto3
import botocore
import os
import time
import pickle
from flask import (
    abort,
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
    session,
    jsonify,
)
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.urls import url_parse

from app.factory import db, PROJECT_NAME
from app.ld import LaunchDarklyApi
from app.models import User, Plan
from app.util import artifical_delay

core = Blueprint("core", __name__)


@core.route("/")
def index():
    """
    Controller for Public home page.
    Includes a server side experiment for trial duration. The duration
    can either be 14 days or 30 days. We show a different variation to
    each user randomly. Then we track the registration rate as our
    conversion event.
    """
    current_app.logger.info(current_app.config)
    if current_user.is_authenticated:
        return redirect(url_for("core.dashboard"))

    user = current_user.get_ld_user()
    req_headers = request.user_agent
    current_app.logger.error(req_headers)
    user['custom']['browser'] = req_headers.browser
    session["ld_user"] = user

    flag_name = "trial-duration"
    trial_duration = current_app.ldclient.variation_detail(flag_name, user, "15")

    start_time = time.time()

    if current_app.ldclient.variation('artificial-delay', user, False):
        artifical_delay(trial_duration.value)

    # Calculate the server processing time based on flag evaluation
    end_time = time.time() - start_time
    data_export = {
        "flag": flag_name,
        "variation": trial_duration.variation_index,
        "time": end_time,
    }
    current_app.ldclient.track("trial-rendering", user, data_export)

    session["trial_duration"] = trial_duration.value
    bootstrap = current_app.ldclient.all_flags_state(user)
    user_template = json.dumps(user)
    broken_release = current_app.ldclient.variation("accessibility-styling", user, False)
    register_color = current_app.ldclient.variation("registration-button-color", user, "#28A745")

    return render_template("home.html", all_flags=bootstrap.to_json_string(), register_color=register_color, broken_release=broken_release, user_template=user_template, trial_duration=trial_duration.value)


@core.route("/dashboard")
@login_required
def dashboard():
    theme = request.args.get("theme")
    user = current_user.get_ld_user()
    user['agent'] = request.headers.get('User-Agent')

    if theme:
        updateTheme(theme)

    dark_theme = current_app.ldclient.variation(
        "dark-theme", user, False
    )

    user_template = json.dumps(user)
    bootstrap = current_app.ldclient.all_flags_state(user)

    set_theme = "{0}/index.html".format(current_user.set_path)

    return render_template(
        set_theme,
        title="Home",
        dark_theme=dark_theme,
        user_template=user_template,
        all_flags=bootstrap.to_json_string(),
    )

def updateTheme(theme):

    if theme == "dark":
        current_user.set_path = "beta"
    else:
        current_user.set_path = "default"

    db.session.commit()


@core.route("/dark")
def darkTheme():
    return render_template(set_theme, title="Dark Theme")


@core.route("/experiments")
def experiments():
    theme = request.args.get("theme")
    if theme:
        updateTheme(theme)

    set_theme = "{0}/exp.html".format(current_user.set_path)

    user = current_user.get_ld_user()
    random_user = current_user.get_random_ld_user()

    user_template = json.dumps(user)
    bootstrap = current_app.ldclient.all_flags_state(user)

    show_nps = current_app.ldclient.variation("show-nps-survery", random_user, False)

    return render_template(
        set_theme,
        title="Experiments",
        show_nps=show_nps,
        random_user=random_user,
        user_template=user_template,
        all_flags=bootstrap.to_json_string(),
    )


@core.route("/operational")
def operational():
    theme = request.args.get("theme")
    if theme:
        updateTheme(theme)

    set_theme = "{0}/operation.html".format(current_user.set_path)

    bootstrap = current_app.ldclient.all_flags_state(current_user.get_ld_user())

    return render_template(
        set_theme, title="Operational", all_flags=bootstrap.to_json_string()
    )


@core.route("/dataexport")
def dataexport():

    theme = request.args.get("theme")

    if theme:
        updateTheme(theme)

    user = current_user.get_ld_user()
    session["ld_user"] = user

    set_theme = "{0}/dataexport.html".format(current_user.set_path)

    return render_template(set_theme, title="dataexport")


@core.route("/release")
def release():
    theme = request.args.get("theme")
    if theme:
        updateTheme(theme)

    set_theme = "{0}/release.html".format(current_user.set_path)
    return render_template(set_theme, title="Dark Theme")


@core.route("/register", methods=["GET", "POST"])
def register():
    # track registration attempts
    # ld_user will be in session if user got to the registration
    # page by clicking a link on the home page (where they saw the ab test)
    if session.get("ld_user"):
        current_app.logger.info(
            "Sending track event for {0}".format(session.get("ld_user"))
        )
        current_app.ldclient.track("started-registration", session["ld_user"])

    if current_user.is_authenticated:
        return redirect(url_for("core.dashboard"))

    if request.method == "POST":
        user = User(email=request.form["userEmail"])
        # check if userName exist
        if User.query.filter_by(email=request.form["userEmail"]).first() is not None:
            flash("Email is already taken. Please choose another email")
            return redirect(url_for("core.register"))
        # check if passwords match
        if request.form["inputPassword"] != request.form["confirmPassword"]:
            flash("Passwords must match")
            return redirect(url_for("core.register"))
        user.set_password(request.form["inputPassword"])
        db.session.add(user)
        db.session.commit()
        flash("Congratulations, you are now a registered user!")

        # track registration completion
        # ld_user will be in session if user got to the registration
        # page by clicking a link on the home page (where they saw the ab test)
        if session.get("ld_user"):
            current_app.logger.info(
                "Sending track event for {0}".format(session.get("ld_user"))
            )
            current_app.ldclient.track("registered", session["ld_user"])

        login_user(user)
        return redirect(url_for("core.dashboard"))
    return render_template("beta/auth/register.html", title="Support Request")


@core.route("/login", methods=["GET", "POST"])
def login(theme="default"):
    if current_user.is_authenticated:
        return redirect(url_for("core.dashboard"))
    if request.method == "POST":
        user = User.query.filter_by(email=request.form["userEmail"]).first()
        if user is None or not user.check_password(request.form["inputPassword"]):
            flash("Invalid username or password")
            return redirect(url_for("core.login"))
        login_user(user)
        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("core.dashboard")
        return redirect(next_page)
    return render_template("beta/auth/login.html", title="Sign In")


@core.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


@core.route("/profile")
@login_required
def profile():
    bootstrap = current_app.ldclient.all_flags_state(current_user.get_ld_user())

    user = User.query.filter_by(id=current_user.id).first()
    return render_template(
        "default/profile.html", user=user, all_flags=bootstrap.to_json_string()
    )


@core.route("/people")
@login_required
def people():
    bootstrap = current_app.ldclient.all_flags_state(current_user.get_ld_user())
    page = request.args.get("page", 1, type=int)
    users = User.query.order_by(User.id).paginate(page, 15, False)
    next_url = url_for("core.people", page=users.next_num) if users.has_next else None
    prev_url = url_for("core.people", page=users.prev_num) if users.has_prev else None
    return render_template(
        "default/people.html",
        users=users.items,
        next_url=next_url,
        prev_url=prev_url,
        all_flags=bootstrap.to_json_string(),
    )


@core.route("/settings")
@login_required
def settings():
    bootstrap = current_app.ldclient.all_flags_state(current_user.get_ld_user())
    plans = Plan.query.all()
    return render_template(
        "default/settings.html", plans=plans, all_flags=bootstrap.to_json_string()
    )


@core.route("/upgrade")
@login_required
def upgrade():
    current_user.plan_id = request.args.get("plan")
    db.session.commit()

    return redirect(request.referrer)


@core.route("/environments")
def environments():
    webhook = current_app.ldclient.variation(
        "environments-webhook", current_user.get_ld_user(), False
    )
    url = url_parse(request.url)
    subdomain = url.host.split(".")[0]

    if subdomain == "admin" and webhook:
        try:
            ld = LaunchDarklyApi(os.environ.get("LD_API_KEY"))
            project = ld.get_project(PROJECT_NAME)
            project_pick = pickle.dumps(project)
            current_app.redis_client.set(PROJECT_NAME, project_pick)
            return jsonify({"response": 200})
        except Exception as e:
            current_app.logger.error(e)
            abort(500)
    else:
        abort(403)

app/templates/partials/chat.html
{% block chatbox %}
<!-- Chat Box --> 
<div class="chatbox chatbox--tray" style="display:none;" >
        <div class="chatbox__title">
            <h5><a href="#">Customer Service</a></h5>
            <button class="chatbox__title__tray">
                <span></span>
            </button>
            <button class="chatbox__title__close">
                <span>
                    <svg viewBox="0 0 12 12" width="12px" height="12px">
                        <line stroke="#FFFFFF" x1="11.75" y1="0.25" x2="0.25" y2="11.75"></line>
                        <line stroke="#FFFFFF" x1="11.75" y1="11.75" x2="0.25" y2="0.25"></line>
                    </svg>
                </span>
            </button>
        </div>
        <div class="chatbox__body">
            <div class="chatbox__body__message chatbox__body__message--left">
                <img src="https://s3.amazonaws.com/uifaces/faces/twitter/brad_frost/128.jpg" alt="Picture">
                <p>Thanks for your interest in LaunchDarkly! How can I help today?</p>
            </div>
            <!-- <div class="chatbox__body__message chatbox__body__message--right">
                <img src="https://s3.amazonaws.com/uifaces/faces/twitter/arashmil/128.jpg" alt="Picture">
                <p>Nulla vel turpis vulputate, tincidunt lectus sed, porta arcu.</p>
            </div> -->

        </div>
        <textarea class="chatbox__message" placeholder="Write something interesting"></textarea>
        <!-- <form class="chatbox__credentials">
            <div class="form-group">
                <label for="inputName">Name:</label>
                <input type="text" class="form-control" id="inputName" required>
            </div>
            <div class="form-group">
                <label for="inputEmail">Email:</label>
                <input type="email" class="form-control" id="inputEmail" required>
            </div>
            <button type="submit" class="btn btn-success btn-block">Enter Chat</button>
        </form> -->
    </div>
{% endblock %}

app/templates/partials/footer.html
{% block footer %}
    <!-- ** *Note* LaunchDarkly is initialized in the header ** -->

    <small>Support Service Version: {{ config['VERSION'] }}</small>
    <!-- Bootstrap Core JavaScript -->
    <script src="{{ url_for('static', filename='light/vendor/bootstrap/js/bootstrap.min.js') }}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{ url_for('static', filename='light/vendor/metisMenu/metisMenu.min.js') }}"></script>

    <!-- Morris Charts JavaScript -->
    <script src="{{ url_for('static', filename='light/vendor/raphael/raphael.min.js') }}"></script>
    <script src="{{ url_for('static', filename='light/vendor/morrisjs/morris.min.js') }}"></script>
    <script src="{{ url_for('static', filename='light/data/morris-data.js') }}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{{ url_for('static', filename='light/dist/js/sb-admin-2.js') }}"></script>
   <script>
       // Show Widgets Code
       var displayWidget = document.getElementById('widgets');
       var renderButton = function() {
            var showFeature = ldclient.variation("show-widgets", false);
            var displayWidget = document.getElementById('widgets');
            if (displayWidget) {
                if (showFeature) {
                    displayWidget.style.display = "block";
                } else {
                    displayWidget.style.display = "none";
                }
            }


       }

       // ChatBox Code
       var renderChatbox = function() {
           var showFeature = ldclient.variation("chatbox", false);

           if (showFeature) {
               (function($) {
                    $(document).ready(function() {
                        var $chatbox = $('.chatbox'),
                            $chatboxTitle = $('.chatbox__title'),
                            $chatboxTitleClose = $('.chatbox__title__close'),
                            $chatboxCredentials = $('.chatbox__credentials');
                        $chatbox.removeClass('chatbox--closed', 'chatbox--tray').css('display', 'block');
                        $chatboxTitle.on('click', function() {
                            $chatbox.toggleClass('chatbox--tray');
                        });
                        $chatboxTitleClose.on('click', function(e) {
                            e.stopPropagation();
                            $chatbox.addClass('chatbox--closed');
                        });
                        $chatbox.on('transitionend', function() {
                            if ($chatbox.hasClass('chatbox--closed')) $chatbox.slideDown();
                        });
                        setTimeout(function(){ $chatboxTitle.trigger('click'); }, 700);
                    });
                })(jQuery);
           } else {
            $('.chatbox').hide();
            console.log('see ya')
           }
       }

        // a11y code
        var a11y = function(){
            console.log("Updating Accessibility")
            var register_link = document.getElementsByClassName("register_link");
            var brand_flag = ldclient.variationDetail("registration-button-color", "#28A745");
            console.log(brand_flag)
            if(register_link){
                for (var i=0, len=register_link.length|0; i<len; i=i+1|0) {
                    register_link[i].style.backgroundColor = brand_flag.value;
                }
            }
       }

       var checkReload = function(){
            var reload = ldclient.variation("force-page-reload", false)
            checkExists = document.cookie.indexOf('force_reload=');
            if (reload && checkExists == -1) {
                console.log("Reloading")
                var now = new Date();
                var time = now.getTime();
                time += 3600 * 1000;
                now.setTime(time);
                location.reload();
                // Write cookie so we don't keep reloading forever
                document.cookie = 'force_reload=' + Date.now().toString() + '; expires=' + now.toUTCString() +
'; path=/';
            }
       }

       // Track page loadtime on page refresh and call LD track
        window.onload = function () {
            var loadTime = window.performance.timing.domContentLoadedEventEnd-window.performance.timing.navigationStart; 
            console.log('Page load time is '+ loadTime);
            ldclient.track("PageLoadtime", null, loadTime)
        }

       // LD Client Rendering
       ldclient.waitForInitialization().then(function() {
            console.log("It's now safe to request feature flags");
            console.log(ldclient);
            renderButton();
            renderChatbox();
            a11y();
       })

       ldclient.on('change', function() {
           console.log('this should change')
           renderButton();
           renderChatbox();
           a11y();
           checkReload();
       });

</script>
{% endblock %}

app/templates/partials/head.html
{% block header %}
<!-- Header scripts could go here -->
<script crossorigin="anonymous" src="https://unpkg.com/launchdarkly-js-client-sdk@2"></script>
<script>
        var ldclient = LDClient.initialize("{{ config['LD_FRONTEND_KEY'] }}", {{ user_template | safe }}, options = {
            bootstrap: {{ all_flags | safe }},
            evaluationReasons: {{ "true" | safe }}
        });
</script>
{% endblock %}

app/templates/partials/nav.html
{% block navbar %}
{% if current_user.is_authenticated %}
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('core.dashboard') }}">SupportService</a>
        </div>

        <!-- /.navbar-header -->
        <ul class="nav navbar-top-links navbar-right">
            <!-- 
            {# 
                {% if dark_theme %}
                <li>
                    <a href="{{ url_for('updateTheme') }}">
                        <i class="fa fa-adjust fa-fw"></i>
                    </a>
                </li>
                {% endif %}
            #}
            -->
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-messages">
                    <li>
                        <a href="#">
                            <div>
                                <strong>John Smith</strong>
                                <span class="pull-right text-muted">
                                    <em>Yesterday</em>
                                </span>
                            </div>
                            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <strong>John Smith</strong>
                                <span class="pull-right text-muted">
                                    <em>Yesterday</em>
                                </span>
                            </div>
                            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <strong>John Smith</strong>
                                <span class="pull-right text-muted">
                                    <em>Yesterday</em>
                                </span>
                            </div>
                            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text-center" href="#">
                            <strong>Read All Messages</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
                <!-- /.dropdown-messages -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-tasks">
                    <li>
                        <a href="#">
                            <div>
                                <p>
                                    <strong>Task 1</strong>
                                    <span class="pull-right text-muted">40% Complete</span>
                                </p>
                                <div class="progress progress-striped active">
                                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                        <span class="sr-only">40% Complete (success)</span>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <p>
                                    <strong>Task 2</strong>
                                    <span class="pull-right text-muted">20% Complete</span>
                                </p>
                                <div class="progress progress-striped active">
                                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                        <span class="sr-only">20% Complete</span>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <p>
                                    <strong>Task 3</strong>
                                    <span class="pull-right text-muted">60% Complete</span>
                                </p>
                                <div class="progress progress-striped active">
                                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                        <span class="sr-only">60% Complete (warning)</span>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <p>
                                    <strong>Task 4</strong>
                                    <span class="pull-right text-muted">80% Complete</span>
                                </p>
                                <div class="progress progress-striped active">
                                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                        <span class="sr-only">80% Complete (danger)</span>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text-center" href="#">
                            <strong>See All Tasks</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
                <!-- /.dropdown-tasks -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-comment fa-fw"></i> New Comment
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                <span class="pull-right text-muted small">12 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-envelope fa-fw"></i> Message Sent
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-tasks fa-fw"></i> New Task
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text-center" href="#">
                            <strong>See All Alerts</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
                <!-- /.dropdown-alerts -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{{ url_for('core.profile') }}"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li> 
                    {% if dark_theme %}
                    <li><a href="{{ url_for('core.dashboard', theme='dark') }}"><i class="fa fa-adjust fa-fw"></i> Dark Theme</a>
                    </li>
                    {% endif %}
                    <li><a href="{{ url_for('core.settings')}}"><i class="fa fa-cogs fa-fw"></i> Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="{{ url_for('core.logout') }}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    <li>
                        <a href="{{ url_for('core.dashboard') }}"><i class="fa fa-tachometer-alt fa-fw"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="{{ url_for('core.experiments') }}"><i class="fa fa-flask fa-fw"></i> Experimentation</a>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="{{ url_for('core.operational') }}"><i class="fa fa-cogs fa-fw"></i> Operational</a>
                    </li>
                    <li>
                        <a href= "{{ url_for('core.release') }}"><i class="fa fa-clock fa-fw"></i> Release Management</a>
                    </li>
                    <li>
                        <a href="{{ url_for('core.people') }}"><i class="fa fa-users"></i> People </a>
                    </li>
                    <li>
                        <a href="{{ url_for('core.dataexport') }}"><i class="fa fa-database"></i> Data Export </a>
                    </li>
                </ul>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>
{% endif %}
{%- endblock navbar %}